# 上位プロキシを設定する。
#
# cache_peer <hostname> <type> <http-port> <icp-port> [options]
# type      : parent, sibling, multicast
# http-port : http 要求を受け入れるポート番号
# icp-port  : 隣接キャッシュにオブジェクトに関する紹介をするためのポート
#             利用しない場合は、0
# options   : login=user:password (※password はエスケープ等不要です)
#
# cache_peer <proxy-host> parent <proxy-port> 0 login=<user>:<password>
# cache_peer 192.168.1.250 parent 3128 0 
